name: Repository CI Pipelines

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # Make sure code abides by the clang-format.
  lint:
    name: Lint with clang-format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Clang
        uses: egor-tensin/setup-clang@v2
        with:
          version: 22

      - name: Run clang-format
        run: |
          chmod +x format_check.sh ; ./format_check.sh

  # This ensures builds pass for each of the real hardware targets (see CMakePresets.json).
  build:
    name: Build Embedded (${{ matrix.preset }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        preset: [dsp_pedal, board_with_stm32l496zg]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
          cmake-version: "3.27"

      - name: Pull git submodules
        run: |
          git submodule update --init --recursive

      - name: Install GNU Arm Embedded Toolchain
        uses: ryanwinter/arm-none-eabi-gcc@master
        with:
          release: "10.3-2021.10"

      - name: Configure CMake for ${{ matrix.preset }}
        run: cmake --preset=${{ matrix.preset }}

      - name: Build ${{ matrix.preset }}
        run: cmake --build build/${{ matrix.preset }}
